//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemeBorsa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorsaIslem
    {
        public int IslemID { get; set; }
        public int BorsaID { get; set; }
        public double Alis { get; set; }
        public double Satis { get; set; }
        public double Degisim { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Borsa Borsa { get; set; }
    }
}
