//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemeBorsa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borsa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borsa()
        {
            this.BorsaKullaniciIslem = new HashSet<BorsaKullaniciIslem>();
            this.BorsaIslem = new HashSet<BorsaIslem>();
        }
    
        public int BorsaID { get; set; }
        public int Tur { get; set; }
        public string Adi { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorsaKullaniciIslem> BorsaKullaniciIslem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorsaIslem> BorsaIslem { get; set; }
    }
}
