//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemeBorsa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorsaKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorsaKullanici()
        {
            this.BorsaKullaniciIslem = new HashSet<BorsaKullaniciIslem>();
        }
    
        public int KullaniciID { get; set; }
        public int Tur { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string TcKimlikNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorsaKullaniciIslem> BorsaKullaniciIslem { get; set; }
    }
}
