//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemeBorsa.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BorsaEntities : DbContext
    {
        public BorsaEntities()
            : base("name=BorsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Borsa> Borsa { get; set; }
        public virtual DbSet<BorsaKullanici> BorsaKullanici { get; set; }
        public virtual DbSet<BorsaKullaniciIslem> BorsaKullaniciIslem { get; set; }
        public virtual DbSet<BorsaIslem> BorsaIslem { get; set; }
    }
}
